import {OrbitaNavbar} from '@/components/orbita-landing/OrbitaNavbar';
import {OrbitaFooter} from '@/components/orbita-landing/OrbitaFooter';
import {PilotInquiry} from '@/components/orbita-landing/PilotInquiry';
import s from './pilot.module.css';
export default function Home(){return <main className={s.site}>
 <a className={s.skip} href="#servicio">Saltar al contenido</a><OrbitaNavbar/>
 <section className={s.hero}><div><p className={s.eyebrow}>CONTENIDO INMOBILIARIO · PILOTO ASISTIDO</p><h1>Una propiedad.<br/><em>Una historia<br/>que mostrar.</em></h1><p className={s.intro}>Convierte las imágenes de tu inmueble en una presentación que puedas compartir. Video, una página dedicada y una llamada a la acción para el siguiente interesado.</p><div className={s.actions}><a className={s.primary} href="#consulta">Solicitar propuesta ↗</a><a href="#demo">Ver la muestra ↓</a></div><p className={s.note}>Empezamos con una propiedad. Alcance, precio y plazo por escrito.</p></div><figure><img src="/orbita/demo/poster.jpg" alt="Fotograma del video de muestra de La Floresta"/><figcaption><span>LA FLORESTA / MUESTRA</span><span>01 — ÓRBITA</span></figcaption></figure></section>
 <section id="demo" className={s.section}><div className={s.heading}><div><p className={s.eyebrow}>01 / VER ANTES DE PEDIR</p><h2>Una muestra que<br/><em>puedes reproducir.</em></h2></div><p>Este video pregrabado está incluido en el proyecto. Muestra una dirección visual; no es un render en vivo ni un recorrido 3D interactivo.</p></div><video controls playsInline preload="none" poster="/orbita/demo/poster.jpg" aria-label="Video de muestra de La Floresta"><source src="/orbita/demo/la-floresta-3d.mp4" type="video/mp4"/>Tu navegador no puede reproducir el video.</video><p className={s.note}>Pieza visual de ejemplo, no anuncio de una propiedad disponible. No contiene información verbal necesaria para entender el servicio. <a href="/orbita/demo/la-floresta-3d.mp4">Abrir video</a> · <a href="/p/la-floresta-199/">Ver la página de muestra ↗</a></p></section>
 <section id="servicio" className={`${s.section} ${s.service}`}><p className={s.eyebrow}>02 / UN ENCARGO CONCRETO</p><h2>Tu primer paquete<br/><em>de contenido.</em></h2><div className={s.cards}>{[['01','Video de presentación','Una pieza editada a partir del material aprobado. Acordamos duración, formato, textos y estilo antes de producir.'],['02','Micrositio de propiedad','Una página con imágenes, información validada por ti y un enlace de contacto. Hosting y dominio se detallan en la propuesta.'],['03','Entrega y revisión','Archivos finales, enlace de la página y revisión del recorrido. Definimos de antemano las revisiones incluidas.']].map(([n,t,p])=><article key={n}><span>{n}</span><h3>{t}</h3><p>{p}</p></article>)}</div><div className={s.scope}><h3>Lo que necesitamos de ti</h3><p>Fotos que puedas utilizar, datos correctos de la propiedad, objetivo del contenido y contacto que debe aparecer. No publiques direcciones privadas o datos de terceros sin autorización.</p><p>La propuesta confirma viabilidad y presupuesto. No incluye publicación automática en portales, integración MLS, analítica ni reconstrucción 3D salvo acuerdo específico y validación técnica.</p></div></section>
 <section className={s.section}><p className={s.eyebrow}>03 / DEL MATERIAL A LA ENTREGA</p><h2>Con revisión humana,<br/><em>en cada paso.</em></h2><ol className={s.steps}>{[['Revisamos','Evaluamos una muestra de material y definimos qué es posible producir.'],['Acordamos','Propuesta con entregables, precio, fecha, revisiones y forma de pago.'],['Producimos','Preparamos una versión para tu revisión y corregimos dentro del alcance.'],['Entregamos','Verificamos archivos, página y enlace de contacto antes del cierre.']].map(([title,body],i)=><li key={title}><span>0{i+1}</span><h3>{title}</h3><p>{body}</p></li>)}</ol></section>
 <section id="consulta" className={`${s.section} ${s.inquiry}`}><div><p className={s.eyebrow}>04 / EMPECEMOS CON UNA PROPIEDAD</p><h2>¿Qué quieres<br/><em>presentar?</em></h2><p>Cuéntanos qué material tienes y dónde quieres compartir el resultado. Revisaremos el encargo antes de acordar precio y plazo.</p><a href="mailto:contact@alicelabs.site">contact@alicelabs.site ↗</a></div><PilotInquiry/></section><OrbitaFooter/>
 </main>}
